export const countries = [
          { id: 1, name: 'United States', currency_code: 'USD', currency_symbol: '$', convert_factor: 1.00 },
          { id: 2, name: 'Algeria', currency_code: 'DZD', currency_symbol: 'DA', convert_factor: 129.87 },
          { id: 3, name: 'Angola', currency_code: 'AOA', currency_symbol: 'Kz', convert_factor: 922.78 },
          { id: 4, name: 'Botswana', currency_code: 'BWP', currency_symbol: 'P', convert_factor: 13.00 },
          { id: 5, name: 'Burundi', currency_code: 'BIF', currency_symbol: 'FBu', convert_factor: 2000.00 },
          { id: 6, name: 'Cabo Verde', currency_code: 'CVE', currency_symbol: '', convert_factor: 110.00 },
          { id: 7, name: 'Benin', currency_code: 'XOF', currency_symbol: 'CFA', convert_factor: 563.5 },
          { id: 8, name: 'Burkina Faso', currency_code: 'XOF', currency_symbol: 'CFA', convert_factor: 563.5 },
          { id: 9, name: 'Guinea-Bissau', currency_code: 'XOF', currency_symbol: 'CFA', convert_factor: 563.5 },
          { id: 10, name: "Côte d'Ivoire", currency_code: 'XOF', currency_symbol: 'CFA', convert_factor: 563.5 },
          { id: 11, name: 'Mali', currency_code: 'XOF', currency_symbol: 'CFA', convert_factor: 563.5 },
          { id: 12, name: 'Niger', currency_code: 'XOF', currency_symbol: 'CFA', convert_factor: 563.5 },
          { id: 13, name: 'Senegal', currency_code: 'XOF', currency_symbol: 'CFA', convert_factor: 563.5 },
          { id: 14, name: 'Togo', currency_code: 'XOF', currency_symbol: 'CFA', convert_factor: 563.5 },
          { id: 15, name: 'Cameroon', currency_code: 'XAF', currency_symbol: 'FCFA', convert_factor: 563.5 },
          { id: 16, name: 'Central African Republic', currency_code: 'XAF', currency_symbol: 'FCFA', convert_factor: 563.5 },
          { id: 17, name: 'Chad', currency_code: 'XAF', currency_symbol: 'FCFA', convert_factor: 563.5 },
          { id: 18, name: 'Republic of the Congo', currency_code: 'XAF', currency_symbol: 'FCFA', convert_factor: 563.5 },
          { id: 19, name: 'Equatorial Guinea', currency_code: 'XAF', currency_symbol: 'FCFA', convert_factor: 563.5 },
          { id: 20, name: 'Gabon', currency_code: 'XAF', currency_symbol: 'FCFA', convert_factor: 563.5 },
          { id: 21, name: 'Comoros', currency_code: 'KMF', currency_symbol: 'FC', convert_factor: 420.00 },
          { id: 22, name: 'Democratic Republic of the Congo', currency_code: 'CDF', currency_symbol: 'FC', convert_factor: 2300.00 },
          { id: 23, name: 'Djibouti', currency_code: 'DJF', currency_symbol: 'Fdj', convert_factor: 178.00 },
          { id: 24, name: 'Egypt', currency_code: 'EGP', currency_symbol: 'LE', convert_factor: 30.00 },
          { id: 25, name: 'Eritrea', currency_code: 'ERN', currency_symbol: 'Nkf', convert_factor: 16.00 },
          { id: 26, name: 'Ethiopia', currency_code: 'ETB', currency_symbol: 'Br', convert_factor: 55.00 },
          { id: 27, name: 'Gambia', currency_code: 'GMD', currency_symbol: 'D', convert_factor: 63.00 },
          { id: 28, name: 'Ghana', currency_code: 'GHS', currency_symbol: '₵', convert_factor: 12.00 },
          { id: 29, name: 'Guinea', currency_code: 'GNF', currency_symbol: 'FG', convert_factor: 9500.00 },
          { id: 30, name: 'Kenya', currency_code: 'KES', currency_symbol: 'KSh', convert_factor: 160.00 },
          { id: 31, name: 'Lesotho', currency_code: 'LSL', currency_symbol: 'L', convert_factor: 18.00 },
          { id: 32, name: 'Liberia', currency_code: 'LRD', currency_symbol: '$', convert_factor: 160.00 },
          { id: 33, name: 'Libya', currency_code: 'LYD', currency_symbol: 'LD', convert_factor: 5.00 },
          { id: 34, name: 'Madagascar', currency_code: 'MGA', currency_symbol: 'Ar', convert_factor: 4200.00 },
          { id: 35, name: 'Malawi', currency_code: 'MWK', currency_symbol: 'MK', convert_factor: 1200.00 },
          { id: 36, name: 'Mauritania', currency_code: 'MRU', currency_symbol: 'UM', convert_factor: 35.00 },
          { id: 37, name: 'Mauritius', currency_code: 'MUR', currency_symbol: 'Rs', convert_factor: 45.00 },
          { id: 38, name: 'Morocco', currency_code: 'MAD', currency_symbol: 'DH', convert_factor: 10.00 },
          { id: 39, name: 'Mozambique', currency_code: 'MZN', currency_symbol: 'Mt', convert_factor: 65.00 },
          { id: 40, name: 'Namibia', currency_code: 'NAD', currency_symbol: 'N$', convert_factor: 19.00 },
          { id: 41, name: 'Nigeria', currency_code: 'NGN', currency_symbol: '₦', convert_factor: 1500.00 },
          { id: 42, name: 'Rwanda', currency_code: 'RWF', currency_symbol: 'FRw', convert_factor: 1050.00 },
          { id: 43, name: 'São Tomé and Príncipe', currency_code: 'STN', currency_symbol: 'Db', convert_factor: 25.00 },
          { id: 44, name: 'Seychelles', currency_code: 'SCR', currency_symbol: 'Rs', convert_factor: 14.00 },
          { id: 45, name: 'Sierra Leone', currency_code: 'SLL', currency_symbol: 'Le', convert_factor: 24.00 },
          { id: 46, name: 'Somalia', currency_code: 'SOS', currency_symbol: 'Sh.So.', convert_factor: 575.00 },
          { id: 47, name: 'South Africa', currency_code: 'ZAR', currency_symbol: 'R', convert_factor: 18.00 },
          { id: 48, name: 'South Sudan', currency_code: 'SSP', currency_symbol: '£', convert_factor: 375.00 },
          { id: 49, name: 'Sudan', currency_code: 'SDG', currency_symbol: 'LS', convert_factor: 600.00 },
          { id: 50, name: 'Eswatini', currency_code: 'SZL', currency_symbol: 'L', convert_factor: 18.00 },
          { id: 51, name: 'Tanzania', currency_code: 'TZS', currency_symbol: 'TSh', convert_factor: 2300.00 },
          { id: 52, name: 'Tunisia', currency_code: 'TND', currency_symbol: 'DT', convert_factor: 3.10 },
          { id: 53, name: 'Uganda', currency_code: 'UGX', currency_symbol: 'USh', convert_factor: 3800.00 },
          { id: 54, name: 'Zambia', currency_code: 'ZMW', currency_symbol: 'K', convert_factor: 18.00 },
          { id: 55, name: 'Zimbabwe', currency_code: 'ZWG', currency_symbol: 'ZiG', convert_factor: 200000.00 },
          { id: 56, name: 'European Union', currency_code: 'EUR', currency_symbol: '€', convert_factor: 0.85 }
        ];